export default { 
    GET_VENDORS_REQUEST:'GET_VENDORS_REQUEST',
    GET_VENDORS_SUCCESS:'GET_VENDORS_SUCCESS',
    GET_VENDORS_FAILED:'GET_VENDORS_FAILED',
    GET_VENDORS_FINISHED:'GET_VENDORS_FINISHED',
}